export type UserRole =
  | 'PLATFORM_OWNER'
  | 'SUPER_ADMIN'
  | 'COLLEGE_ADMIN'
  | 'STUDENT'
  | 'FACULTY_MENTOR'
  | 'PROGRAM_ADMIN'
  | 'TRAINER'
  | 'PLACEMENT_COORDINATOR'
  | 'SUPER_ADMIN';

export const STAFF_ROLES: UserRole[] = [
  'PLATFORM_OWNER',
  'SUPER_ADMIN',
  'COLLEGE_ADMIN',
  'FACULTY_MENTOR',
  'PROGRAM_ADMIN',
  'TRAINER',
  'PLACEMENT_COORDINATOR',
];
