from __future__ import annotations

from typing import Any
from pydantic import BaseModel, Field


# ── Shared sub-models ─────────────────────────────────────────────────────────

class ProjectSummary(BaseModel):
    title: str
    tech_stack: list[str] = Field(default_factory=list)
    description: str = ""


class PreviousTurn(BaseModel):
    question_text: str
    student_answer: str
    difficulty: str
    technical_score: float | None = None
    feedback: str | None = None


# ── Resume / candidate profile ────────────────────────────────────────────────

class CandidateSkills(BaseModel):
    languages: list[str] = Field(default_factory=list)
    frameworks: list[str] = Field(default_factory=list)
    databases: list[str] = Field(default_factory=list)
    tools: list[str] = Field(default_factory=list)


class CandidateResume(BaseModel):
    name: str = ""
    experience_level: str = "fresher"
    skills: CandidateSkills = Field(default_factory=CandidateSkills)
    projects: list[ProjectSummary] = Field(default_factory=list)
    summary: str = ""


# ── Interview state (persisted in Redis session:{id}:state) ───────────────────

class StateUpdate(BaseModel):
    """Subset returned by LLM each turn — applied by Node.js to Redis state."""
    mark_topic_completed: str | None = None
    add_to_do_not_ask: str | None = None


class InterviewState(BaseModel):
    session_id: str = ""
    student_id: str = ""
    topic_curriculum: list[str] = Field(default_factory=list)
    completed_topics: list[str] = Field(default_factory=list)
    active_topic: str = "General"
    active_topic_question_count: int = 0
    max_questions_per_topic: int = 3
    do_not_ask_or_repeat: list[str] = Field(default_factory=list)
    current_turn: int = 1
    max_turns: int = 10
    current_difficulty: str = "EASY"
    candidate_performance_trend: str = "stable"
    consecutive_weak_answers: int = 0


# ── Rubric ─────────────────────────────────────────────────────────────────────

class ScoringBands(BaseModel):
    high: str = ""
    mid: str = ""
    low: str = ""


class Rubric(BaseModel):
    key_concepts: list[str] = Field(default_factory=list)
    strong_indicators: list[str] = Field(default_factory=list)
    weak_indicators: list[str] = Field(default_factory=list)
    scoring_bands: ScoringBands = Field(default_factory=ScoringBands)
    follow_up_probes: list[str] = Field(default_factory=list)


# ── evaluate-response request metadata ───────────────────────────────────────

class EvaluateResponseMetadata(BaseModel):
    """All context passed by Node.js alongside the audio file."""
    # Core turn info
    question_text: str
    difficulty: str = "EASY"
    turn_number: int = 1
    session_id: str = ""
    student_id: str = ""
    domain: str | None = None

    # Context blocks injected into LLM prompt
    interview_state: InterviewState = Field(default_factory=InterviewState)
    short_term_context: list[str] = Field(default_factory=list)   # last 10 summaries
    current_rubric: Rubric | None = None                           # rubric for THIS question
    resume: CandidateResume = Field(default_factory=CandidateResume)

    # Legacy field kept for backward compat
    previous_turns: list[PreviousTurn] = Field(default_factory=list)


# ── LLM structured response ───────────────────────────────────────────────────

class LLMInterviewResponse(BaseModel):
    """
    The exact JSON the LLM must return from a single conduct_interview call.
    Parsed and validated before being used by the router.
    """
    analysis: str = ""
    update_state: StateUpdate = Field(default_factory=StateUpdate)
    conversational_response: str = ""          # spoken to candidate (TTS)
    next_question_text: str = ""               # clean question only, stored in DB
    rubric_for_next_question: Rubric = Field(default_factory=Rubric)
    context_summary: str = ""                  # 2-3 line digest → Redis + Vector DB
    technical_score: float = Field(default=5.0, ge=0, le=10)
    feedback: str = ""
    strengths: str = ""
    weaknesses: str = ""
    next_recommended_difficulty: str = "EASY"


# ── Full combined result returned to Node.js ─────────────────────────────────

class CombinedEvalResult(BaseModel):
    """Full response: LLM scores + audio signal metrics + rubric + state update."""
    # Transcript
    transcript: str
    stt_raw: str

    # LLM evaluation fields (0-10 scale; Node.js converts to 0-100)
    technical_score: float = Field(ge=0, le=10)
    feedback: str
    strengths: str
    weaknesses: str
    next_recommended_difficulty: str

    # Next question + rubric (generated by LLM in same call)
    conversational_response: str = ""
    next_question_text: str = ""
    rubric_for_next_question: dict[str, Any] = Field(default_factory=dict)

    # State management
    update_state: dict[str, Any] = Field(default_factory=dict)

    # Context summary for Redis + Vector DB storage
    context_summary: str = ""

    # Audio signal metrics (waveform + transcript, NOT from LLM)
    pace_wpm: float = 0.0
    filler_count: int = 0
    fluency_score: float = 0.0
    clarity_score: float = 0.0


# ── Legacy endpoints (kept unchanged) ─────────────────────────────────────────

class QuestionGenerationRequest(BaseModel):
    student_name: str
    skills: list[str] = Field(default_factory=list)
    projects: list[ProjectSummary] = Field(default_factory=list)
    previous_turns: list[PreviousTurn] = Field(default_factory=list)
    difficulty: str = "EASY"
    domain: str | None = None


class GeneratedQuestionResponse(BaseModel):
    question_text: str
    difficulty: str
    category: str | None = None


class TurnEvaluationRequest(BaseModel):
    question_text: str
    student_answer: str
    difficulty: str
    turn_number: int = 1
    domain: str | None = None


class TurnEvaluationResponse(BaseModel):
    technical_score: float = Field(ge=0, le=10)
    communication_score: float = Field(ge=0, le=10)
    wpm: int = Field(ge=0)
    filler_words: int = Field(ge=0)
    feedback: str
    strengths: str
    weaknesses: str
    next_recommended_difficulty: str


class ListeningEvaluationRequest(BaseModel):
    story_text: str
    question: str
    student_answer: str
    expected_answer: str


class ListeningEvaluationResponse(BaseModel):
    score: float = Field(ge=0, le=10)
    accuracy_level: str
    feedback: str
    missed_key_points: list[str] = Field(default_factory=list)


class ConfigUpdateRequest(BaseModel):
    groq_api_key: str | None = None
    groq_model: str | None = None
    llm_provider: str | None = None
    llm_base_url: str | None = None


class ConfigUpdateResponse(BaseModel):
    status: str
    active_provider: str
    details: dict[str, Any] = Field(default_factory=dict)
